os:
  - Visual Studio 2015

environment:
  CTEST_OUPTUT_ON_FAILURE: ON

branches:
  except:
    - gh-pages

install:
  - set PATH=C:\Python36;%PATH%

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

test_script:
  - cmake --build --target test .
