language: cpp
sudo: false
branches:
  exclude:
    - gh-pages
env:
  - GH_REPO_NAME: CLI11
  - DOXYFILE: $TRAVIS_BUILD_DIR/docs/Doxyfile
  - GH_REPO_REF: github.com/henryiii/CLI11.git
  - secure: yyNmKB1C1bDyvbI/GWkDoUbBoVI+CIuCgftZ/RKnrynfjOe2uaJSVqo9s1L03Pth0mKsBFRAdq4rzLQ/q9v1FG+zVXwyP+gHqbb5SpvY1rNSjfS0JWjF2ZPNVEZ5ewJiV1adfvqen1ri+KB3CDXXi6BdXvmb0+g6ylnO5JuC3zvs60kXLUpAvRnfVMW8mDllEdVRvEVdjAnstiDd+G5U1WGK60JlBosOuvinkKiqTgcqfKHFojlYfoxTOkCtth4sP8fsxCQRP4kNmS7U9w8prFntWZP7n+kXKWfwLTvKg4RWntMt/f6jkQmMH2nDdvsPXvJzS0khPpQSQCIXIrLIcaHJRRTGv8Fg502RUrysgiOxdrcgRvH9AqFn9e48Sal1tkIHygvld7tifv92XowOsQ4VTiFI5PuZ8Ljr3L+SefwowTRK2R1Iz8flIgXHuWsDYbASi3oLPHMzsTXyLJxyoPKFNaXx2TM9S+73PXQcLUlQSdsvDb5AqqSDd5DUwBDSkixXACI+r33iDs64b8DQj8y7Ko0TTahPdmPjY+J9GPy4tLMeuhzvCy4Nfxiqhrf+wRcdWbKcOZsVDtMJPD4f1o1NZ8M8mRMR3YNU7WDbHAivULei01PZrtn0pPlHS8UO+MeCLB0W5KEQNo3CI0/nyuYwGAyytBwNaNwtaiKgMFY=
cache:
  directories:
  - ${TRAVIS_BUILD_DIR}/deps/cmake
matrix:
  include:
  - os: osx
  - compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.5
        - ubuntu-toolchain-r-test
        packages:
        - clang-3.5
    env:
      - COMPILER=3.5
      - DEPLOY_MAT=yes
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env: COMPILER=6
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.7
    env: COMPILER=4.7
install:
- python -c 'import sys; print(sys.version_info[:])'
- if [ "$CXX" = "g++" ]; then export CXX="g++-$COMPILER" CC="gcc-$COMPILER"; fi
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-$COMPILER" CC="clang-$COMPILER"; fi
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- if [ "$TRAVIS_OS_NAME" = "linux" ] ; then CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz" ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ] ; then CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Darwin-x86_64.tar.gz" ; fi
- cd "${DEPS_DIR}"
- |
  if [[ ! -f "${DEPS_DIR}/cmake/bin/cmake" ]] ; then
    echo "Downloading CMake"
    mkdir -p cmake
    travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
  fi
- export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
- cd "${DEPS_DIR}"
- if [ "$(python -c 'import sys; print(sys.version_info[0])')" = "2" ] ; then pip
  install --user pathlib; fi
script:
- cd "${TRAVIS_BUILD_DIR}"
- .ci/travis.sh

after_success:
- echo "${TRAVIS_BRANCH}"
- echo "${TRAVIS_PULL_REQUEST}"
- if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" && "$DEPLOY_MAT" == "yes" ]] ; then echo "Updating docs" &&  cd $TRAVIS_BUILD_DIR && .ci/build_docs.sh ; fi

deploy:
  provider: releases
  api_key:
    secure: bMRTGeFlCmLUJ9EAxCSDPzd5MYGq8Ns2sCr2dCMK/6UL/WeEnwFMkvkBpXvKuG5BHfPft3uttxXI9gtpgTfTym0HCid3QHI5ibl1rKwGXdSx/n++OzZOpwcAgBeM1xSy3qlUSRyZ2zbSgI5KABg4dHezXPRg4S60NFmRNIJtn9zDE847iyGxM7mYtC7aKEZ5KkJAV5MMI8EkicJzBcpREN54NrF8PSw8peCZABIXU27gKvTVf8hxNAwbUzWkUp+YQ693ZA4KGDXIGGN3bngJ2rdxyoLquCEIBDh3Camub+M2PFsKjjHsLRBkVkKXR1BXEJMbROlr9ovlGxL90p7BMZULvVEmGRj2t6ClQdgc8gqyuAaQirr6LpWlXpKjREDgc130ZsEAMY2wTwlaIwjDEIKEyDcEEK4sglCrAg6xQzsNBPMDHYGc6mgbazmvy84UygLl+xXJe2vl/Z875RJBMekBLCKlwgMe+PDO1KGpPOpsLDHwj/Fq3G2+X/WL2ZInaJMhuuvaVJI/AspvEhWWFC6RaoK2q21aTNaDaLFpr0npKKyizcVbdjzEAARL2/sSWka8SWozPCCwDcm2AcunAwnHLylPqZ+Dk2wmrbdztqiALO6GpkMM1ARUIP+laUccVPmCVZeUoTzGLac/QFf6ip+DUG2uQ77q1NjIA6IXCzM=
  skip_cleanup: true
  file: build/include/CLI11.hpp
  on:
    repo: henryiii/CLI11
    tags: true
    condition: $DEPLOY_MAT = yes
