language: cpp
sudo: false
branches:
  exclude:
  - gh-pages
cache:
  directories:
  - ${TRAVIS_BUILD_DIR}/deps/cmake
  - ${TRAVIS_BUILD_DIR}/deps/doxygen
matrix:
  include:
  - compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.5
        - ubuntu-toolchain-r-test
        packages:
        - clang-3.5
    env:
    - COMPILER=3.5
    - DEPLOY_MAT=yes
    - DOXYFILE=$TRAVIS_BUILD_DIR/docs/Doxyfile
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - curl
        - lcov
    env:
    - COMPILER=6
    - COVERALLS=yes
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.7
    env:
    - COMPILER=4.7
  - os: osx
install:
- python -c 'import sys; print(sys.version_info[:])'
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd $TRAVIS_BUILD_DIR && . .ci/prepare_altern.sh
  ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ] ; then cd $TRAVIS_BUILD_DIR && . .ci/build_cmake.sh
  ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ] ; then cd $TRAVIS_BUILD_DIR && . .ci/build_doxygen.sh
  ; fi
- if [ -n "$COVERALLS" ] ; then cd $TRAVIS_BUILD_DIR && . .ci/build_lcov.sh ; fi
- cd "${DEPS_DIR}"
- if [ "$(python -c 'import sys; print(sys.version_info[0])')" = "2" ] ; then pip
  install --user pathlib; fi
script:
- cd "${TRAVIS_BUILD_DIR}"
- .ci/travis.sh
after_success:
- if [ -n "$COVERALLS" ] ; then cd $TRAVIS_BUILD_DIR && .ci/run_codecov.sh ; fi
- echo "${TRAVIS_BRANCH}"
- echo "${TRAVIS_PULL_REQUEST}"
- |
    if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ -n "$DEPLOY_MAT" ]
    then
        echo "Updating docs" && cd $TRAVIS_BUILD_DIR && .ci/build_docs.sh
    fi
deploy:
  provider: releases
  api_key:
    secure: fSUE2bTUyJwMuRuZmHy76bCDSM/XzdHAb3kK1urP1DBa0xbaOORqRxN0KxfRfMaBiQowY9+rJbAE7NpbsInWoDLawgUzDV0jA0lJ3W4gsgBpmriXgD205iaOWPmhWSqfNCyqqJqMprJP9EsE26+jcV54Ge2q0psSJHqD8kEhsb8NLUPkCB82ZCCaJFseCI/u4CJNBbyzGVf42cgAnG2JzX0oCUTLJzMrzc/qFWZRxS/U0l7D8ehrThHGTL9OrVcuWcG3uaFcQ4NvgxeqciXzf6tCZKWCsXId7/2g5jHLZv9FDhaVSz8O6oBN6J2uzQfI+VxvvMW465+dk9s0X/yN6swtHTeA48HbpBwFhqNV2cPU/ZkgVT8a4T1nJRWnAHGFhGEBr0RNMl2bcDrB4tPX/aLBptuDKRVVgmJ+BImgSzEXewGzuwhQ3dJ6zY5IvtO/LDwO7mVnPAzjW81/FwIsS5vYQXBV/sfHw1WpE9mI1GE99laf8UneNqtwPNpU/BAjbb/W4DvC7fyLwf2GDwl35/vOWfDTatilXeYVZetLTReFv8iy4atli2pf/irxbrhCTdiuuJWq18dGfhozvLIEzJMz84+pnT0nXkNshgnJ4rV613G4WfXjOauYOuU80supOZX0raFDDnCF1JNhrIwo9XYZGhIp+qU+NyyzvGsY3zA=
  skip_cleanup: true
  file: build/include/CLI11.hpp
  on:
    repo: CLITools/CLI11
    tags: true
    condition: $DEPLOY_MAT = yes
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/bbdb3befce4c00448d24
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
    secure: G4DlRriUeLR3xYJbI2aZcv4NTY9g+s9IHXiflV2YwfJEAwR2GbtIKKK7WEOlCqVN71EVWarMSGWTOgLarScCP5C+AQw+aKhp5EwA6wraZL5Mu81fiWd7GGBLPwR1JtQHg+xCY3mw5BTaNPHG/DSjl+1/YH0p5hMsf9d1Bwy+0qK212E8Ugn0zr9PFIQR9N3YB6W1l24CzCGcpd2nz+jk7PIOuieIySupkeFuD4RJJrM8NQNMZ2xWQ+Nz5VkpaSN2Zg4Zt/91ck8qsiI74ZgekL74wbt4IFp6vpWAW0G+Sq2Dehfkx1++YX2vKnevwUmYRGvBElhNn2W4z9Xf26EXW9xJlrqmQ2nbt0dMCi7Yok6Yt/PiSf3AU3Xo29dfjlle6b4t7RUjkjRrQlO+eeMy4cZW4rWabIqXbycj3o+STRm9Dv5B9KeO7G6ozKk7WXsbh6GMBa7D1D2nBX5ZN8qlykQktaqonHbWGGKwQPV0Ed/StTZQetr+h4ETNit/NyXj4KjCcdn8/ux4BL97/VPTCTE/GS3AZZ83XX8UGFg/Zkp1HuVrCh4hnGbAe+jdDdtc+pqFiIB3LHM65Euc8xJx1GG+wP9/wio8h7Ex7dOE8B80tuTNA3iCk19jCJDJ1p/Thwcdi5Jr9eKDCKxItN3u48el1sY5Blmpodq6NeN2wMo=
