language: cpp
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake

matrix:
    include:
        - compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-testt
                  packages:
                      - g++-4.9
          env: COMPILER=g++-4.9
        - compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-testt
                  packages:
                      - g++-4.8
          env: COMPILER=g++-4.8
        - compiler: clang
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-testt
                      - llvm-toolchain-precise-3.6
                  packages:
                      - clang-3.6
          env: COMPILER=g++-5

install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
    - cd "${DEPS_DIR}"
    - | 
      if [[ ! -f "${DEPS_DIR}/cmake/bin/cmake" ]] ; then
        echo "Downloading CMake"
        mkdir -p cmake
        travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
      fi
    
    - export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
    - cd "${DEPS_DIR}"

script:
    - cd "${TRAVIS_BUILD_DIR}"
    - .ci/travis.sh

